Update Python scripts
PureStorage-OpenConnect/fusion-client-devkit pull request #22
Opened 2023-04-05 14:12 UTC by andreepyro

This Pull Request introduce 3 changes to the Python scripts:
- **code style**: reformat all code to have consistent code style and move fusion configuration to utils module
- **bug fix** : use two-step volume deletion (raised exception before)
- **improvement**: raise exception on error rather than only print the message - when error happens, there's no point in setting up / tearing down other resources

2023-04-05 15:01 UTC, jankodera-ps commented on python/utils.py
> +def get_fusion_config() -> fusion.Configuration:
Might be worth it to pull from default `~/.pure/fusion.json` if the environment variables are not set, same model we're aiming at with Ansible/Terraform

2023-04-05 15:07 UTC, jankodera-ps approved these changes
A bit hard to review because real changes are interleaved with reformatting. I generally like it, but it may be worth it implement pulling auth info from config as that shouldn't be a too big change and you are already refactoring it out into an utility module. On the other hand, this PR is already big as it is, so it might be better to do that in another one.

2023-04-05 15:08 UTC, jankodera-ps commented
Also please add a changelog fragment about the two-step delete bugfix, that should be tracked.

2023-04-06 11:36 UTC, DenDen039 requested changes

2023-04-06 11:36 UTC, DenDen039 commented on python/utils.py
> +        config.host = os.environ["HOST_ENDPOINT"]
I guess we should change it to `FUSION_HOST` as in Terraform and accept path to fusion, not to the frontdoor directly

2023-04-06 11:36 UTC, DenDen039 commented on python/utils.py
> +    if "TOKEN_ENDPOINT" in os.environ:
In Terraform it is not possible to change tex service. But in Ansible there is another name for env var. We should unify it too
https://github.com/Pure-Storage-Ansible/Fusion-Collection/blob/faf609846ab9782978bfc393d91b0ffc0d2a91d3/plugins/module_utils/fusion.py#L60

2023-04-06 11:36 UTC, DenDen039 commented on python/utils.py
> +def wait_operation_finish(op_id: str, client: fusion.ApiClient) -> fusion.models.operation.Operation:
It is not a part of this PR. But if you refactor scripts, I guess it is better to add some timeout for operation waiting. In Ansible it is `while True` loop because of Ansible paradigms, but I guess it is better to have some timeout in Python scripts. 
@jankodera-ps what do you think?

2023-04-06 11:36 UTC, DenDen039 commented on python/utils.py
> +    if op.status == "Succeeded" or op.error.pure_code == "ALREADY_EXISTS":  # Probably risky but we're going with it
Fusion reserves document name until operation is not fully rolled backed. I guess it is a bug of backend, but it is better to ask David about possible solution

2023-04-06 15:26 UTC, andreepyro commented on python/utils.py
> +        config.host = os.environ["HOST_ENDPOINT"]
Agree, I'll include it to the PR

2023-04-06 15:29 UTC, andreepyro commented on python/utils.py
> +def wait_operation_finish(op_id: str, client: fusion.ApiClient) -> fusion.models.operation.Operation:
Can't hurt I guess.

2023-04-06 15:34 UTC, andreepyro commented on python/utils.py
> +        config.host = os.environ["HOST_ENDPOINT"]
I've just found out there's already a ticket for that and someone else's working on it. So I won't include the change in this PR.

2023-04-06 15:35 UTC, andreepyro commented on python/utils.py
> +    if "TOKEN_ENDPOINT" in os.environ:
Same as with the previous variables - there's already a ticket for that, won't include it here.

2023-04-06 15:35 UTC, andreepyro commented on python/utils.py
> +        config.host = os.environ["HOST_ENDPOINT"]
@DenDen039 please resolve if you don't have any more comments

2023-04-06 15:35 UTC, andreepyro commented on python/utils.py
> +    if "TOKEN_ENDPOINT" in os.environ:
@DenDen039 please resolve if you don't have any more comments

2023-04-11 07:26 UTC, andreepyro commented on python/utils.py
> +def get_fusion_config() -> fusion.Configuration:
Let's make it a separate ticket. In fact, it's inconsistent with a ticket we already have (updating names of the ENV values).

2023-04-11 09:40 UTC, jankodera-ps commented on python/utils.py
> +def get_fusion_config() -> fusion.Configuration:
Can't resolve, probably only you can as the PR author, but yeah, I do agree 😁

2023-04-11 09:40 UTC, jankodera-ps approved these changes

2023-04-11 09:41 UTC, DenDen039 approved these changes

2023-04-11 09:43 UTC, merged