Сhange env variables as in other fusion clients
PureStorage-OpenConnect/fusion-client-devkit pull request #32
Opened 2023-04-25 15:43 UTC by DenDen039

Changed naming of environment variables to match Terraform Provider and Ansible Collection

2023-04-25 17:52 UTC, mikenelson-io approved these changes
We must ensure that these are consistent across all SDKs we provide.

2023-04-26 06:45 UTC, andreepyro requested changes

2023-04-26 06:45 UTC, andreepyro commented on python/utils.py
> +    config.private_key_file = os.environ[ENV_VAR_FUSION_PRIVATE_KEY_FILE]
Here `KeyError` can be raised. Please address this (add try/except or check whether the values are present).

2023-04-26 06:45 UTC, andreepyro commented on python/utils.py
> +        config.host = os.environ[ENV_VAR_FUSION_API_HOST] + "/api/1.0"
Are we sure to append `"/api/1.0"`? Do we have it in other SDKs too?

2023-04-26 07:45 UTC, dimleevik requested changes

2023-04-26 07:45 UTC, dimleevik commented on python/utils.py
> +        config.host = os.environ[ENV_VAR_FUSION_API_HOST] + "/api/1.0"
Maybe it is a better idea to use some library for concationation of two url parts, what if `os.environ[ENV_VAR_FUSION_API_HOST]` will have `/`symbol in the end? Using something like urllib?

2023-04-26 09:23 UTC, andreepyro approved these changes
LGTM

2023-04-26 09:36 UTC, dimleevik approved these changes

2023-04-26 09:37 UTC, merged