Fix AttributeError: module 'time' has no attribute 'now'
PureStorage-OpenConnect/fusion-client-devkit pull request #39
Opened 2023-05-16 09:55 UTC by dszakallas

Fixes the bug

```
File ~/projects/fusion-client-devkit/python/utils.py:71, in wait_operation_finish(op_id, client, timeout)
     55 """
     56 wait_operation_finish wait until operation status is Succeeded or Failed. Then returns you that operation.
     57 if the operation takes longer than expected, it will raise an Exception
   (...)
     68     fusion.models.operation.Operation
     69 """
     70 op_cli = fusion.OperationsApi(client)
---> 71 start_time = time.now()
     72 while True:
     73     op = op_cli.get_operation(op_id)

AttributeError: module 'time' has no attribute 'now'
```

By changing the implementation to use `datetime` and `timedelta` from `datetime`.

2023-05-16 10:58 UTC, andreepyro requested changes
Your changes can be as simple as replacing `time.now()` by `time.time()` without anything else. `datetime` brings here unnecessary logic and makes the code more complicated.

2023-05-16 11:05 UTC, jankodera-ps approved these changes

2023-05-16 11:13 UTC, dszakallas commented
`timedelta` is easier to reason about, as it provides explicit units for measurement. But if the added complexity is undesired, I am happy to change to `time.time()`

2023-05-16 13:11 UTC, andreepyro commented
> timedelta is easier to reason about, as it provides explicit units for measurement. But if the added complexity is undesired, I am happy to change to time.time()

But do you really take advantage of the explicit units for measurement here? To me it seems unnecessary, but it's really subjective :)

2023-05-16 15:49 UTC, DenDen039 approved these changes

2023-05-17 05:56 UTC, andreepyro approved these changes

2023-05-17 05:56 UTC, andreepyro approved these changes

2023-05-18 09:25 UTC, DenDen039 approved these changes

2023-05-18 15:05 UTC, merged